{
TTree *fChain;   //!pointer to the analyzed TTree or TChain

  // Declaration of leaf types
  TLorentzVector  *onia, *muPos, *muNeg;
  int eventNb;
  int runNb;
  int lumiBlock;
  int nPriVtx;
  double vertexWeight;
  double sumPTPV;
  int countTksOfPV;

  double Jpsict;
  double JpsictErr;
  double JpsiMassErr;
  double JpsiVprob;
  double JpsiDistM1;
  double JpsiDphiM1;
  double JpsiDrM1;
  double JpsiDistM2;
  double JpsiDphiM2;
  double JpsiDrM2;
  
  double JpsiMuScleMassCorr;
  double JpsiMuScleMassErr;
  double sigmaPtPos;
  double sigmaPtNeg;


  // trigger
  // Jpsi
  int HLT_Dimuon8_Jpsi_v3;
  int HLT_Dimuon8_Jpsi_v4;
  int HLT_Dimuon8_Jpsi_v5;
  int HLT_Dimuon8_Jpsi_v6;
  int HLT_Dimuon8_Jpsi_v7;
  int HLT_Dimuon10_Jpsi_v3;
  int HLT_Dimuon10_Jpsi_v4;
  int HLT_Dimuon10_Jpsi_v5;
  int HLT_Dimuon10_Jpsi_v6;
  
  int HLT_Dimuon10_Jpsi_Barrel_v1;
  int HLT_Dimuon10_Jpsi_Barrel_v2;
  int HLT_Dimuon10_Jpsi_Barrel_v3;
  int HLT_Dimuon10_Jpsi_Barrel_v5;
  int HLT_Dimuon10_Jpsi_Barrel_v6;
  int HLT_Dimuon10_Jpsi_Barrel_v7;
  int HLT_Dimuon8_Jpsi_v3;
  int HLT_Dimuon8_Jpsi_v4;
  int HLT_Dimuon8_Jpsi_v5;
  int HLT_Dimuon10_Jpsi_v3;
  int HLT_Dimuon10_Jpsi_v4;
  
  

  TCanvas *c1 = new TCanvas("c", "c");
  TH1F *h_nPriVtx[2];
  TH1F *h_vertexWeight[2];
  TH1F *h_sumPTPV[2];
  TH1F *h_countTksOfPV[2];
//  TH1F *h_JpsiMuScleMassCorr[2];
//  TH1F *h_JpsiMuScleMassErr[2];
  TH1F *h_JpsiMassErr[2];
//  TH1F *h_sigmaPtPos[2];
//  TH1F *h_sigmaPtNeg[2];
  TH1F *h_Jpsict[2];
  TH1F *h_JpsictErr[2];
  TH1F *h_JpsiVprob[2];
  TH1F *h_JpsiDistM1[2];
  TH1F *h_JpsiDphiM1[2];
  TH1F *h_JpsiDrM1[2];
  TH1F *h_JpsiDistM2[2];
  TH1F *h_JpsiDphiM2[2];
  TH1F *h_JpsiDrM2[2];
  TH1F *h_jpsi_x[2];
  TH1F *h_jpsi_y[2];
  TH1F *h_jpsi_z[2];
  TH1F *h_jpsi_px[2];
  TH1F *h_jpsi_py[2];
  TH1F *h_jpsi_pz[2];
  TH1F *h_jpsi_t[2];
  TH1F *h_jpsi_Energy[2];
  TH1F *h_jpsi_theta[2];
  TH1F *h_jpsi_costheta[2];
  TH1F *h_jpsi_phi[2];
  TH1F *h_jpsi_rho[2];
  TH1F *h_jpsi_perp2[2];
  TH1F *h_jpsi_pt[2];
  TH1F *h_jpsi_perp[2];
  TH1F *h_jpsi_et2[2];
  TH1F *h_jpsi_et[2];
  TH1F *h_jpsi_M[2];
  TH1F *h_jpsi_Mt2[2];
  TH1F *h_jpsi_Mt[2];
  TH1F *h_jpsi_beta[2];
  TH1F *h_jpsi_gamma[2];
  TH1F *h_jpsi_plus[2];
  TH1F *h_jpsi_minus[2];
  TH1F *h_jpsi_Rap[2];
  TH1F *h_jpsi_eta[2];
  TH1F *h_jpsi_psuedorap[2];
  TH1F *h_muplus_x[2];
  TH1F *h_muplus_y[2];
  TH1F *h_muplus_z[2];
  TH1F *h_muplus_px[2];
  TH1F *h_muplus_py[2];
  TH1F *h_muplus_pz[2];
  TH1F *h_muplus_t[2];
  TH1F *h_muplus_Energy[2];
  TH1F *h_muplus_theta[2];
  TH1F *h_muplus_costheta[2];
  TH1F *h_muplus_phi[2];
  TH1F *h_muplus_rho[2];
  TH1F *h_muplus_perp2[2];
  TH1F *h_muplus_pt[2];
  TH1F *h_muplus_perp[2];
  TH1F *h_muplus_et2[2];
  TH1F *h_muplus_et[2];
//  TH1F *h_muplus_M[2];
  TH1F *h_muplus_Mt2[2];
  TH1F *h_muplus_Mt[2];
  TH1F *h_muplus_beta[2];
  TH1F *h_muplus_gamma[2];
  TH1F *h_muplus_plus[2];
  TH1F *h_muplus_minus[2];
  TH1F *h_muplus_Rap[2];
  TH1F *h_muplus_eta[2];
  TH1F *h_muplus_psuedorap[2];
  TH1F *h_muminus_x[2];
  TH1F *h_muminus_y[2];
  TH1F *h_muminus_z[2];
  TH1F *h_muminus_px[2];
  TH1F *h_muminus_py[2];
  TH1F *h_muminus_pz[2];
  TH1F *h_muminus_t[2];
  TH1F *h_muminus_Energy[2];
  TH1F *h_muminus_theta[2];
  TH1F *h_muminus_costheta[2];
  TH1F *h_muminus_phi[2];
  TH1F *h_muminus_rho[2];
  TH1F *h_muminus_perp2[2];
  TH1F *h_muminus_pt[2];
  TH1F *h_muminus_perp[2];
  TH1F *h_muminus_et2[2];
  TH1F *h_muminus_et[2];
//  TH1F *h_muminus_M[2];
  TH1F *h_muminus_Mt2[2];
  TH1F *h_muminus_Mt[2];
  TH1F *h_muminus_beta[2];
  TH1F *h_muminus_gamma[2];
  TH1F *h_muminus_plus[2];
  TH1F *h_muminus_minus[2];
  TH1F *h_muminus_Rap[2];
  TH1F *h_muminus_eta[2];
  TH1F *h_muminus_psuedorap[2];
  TH1F *h_jpsi_Mag[2];
//  TH1F *h_muminus_Mag[2];
//  TH1F *h_muplus_Mag[2];
  TH1F *h_jpsi_Mag2[2];
//  TH1F *h_muminus_Mag2[2];
//  TH1F *h_muplus_Mag2[2];
  
  
  for(int x = 0; x < 2; x++)
  {
    h_nPriVtx[x] = new TH1F("","",50,0,50);
    h_vertexWeight[x] = new TH1F("","",150,0,150);
  h_sumPTPV[x] = new TH1F("","",500,0,250);
  h_countTksOfPV[x] = new TH1F("","",150,0,150);
//  h_JpsiMuScleMassCorr[x] = new TH1F("","",500,0,50);
//  h_JpsiMuScleMassErr[x] = new TH1F("","",5000,-50,50);
  h_JpsiMassErr[x] = new TH1F("","",250,0,0.05);
//  h_sigmaPtPos[x] = new TH1F("","",5000,-50,50);
//  h_sigmaPtNeg[x] = new TH1F("","",5000,-50,50);
  h_Jpsict[x] = new TH1F("","",25,0,2.5);
  h_JpsictErr[x] = new TH1F("","",500,0,0.2);
  h_JpsiVprob[x] = new TH1F("","",100,0,1.1);
  h_JpsiDistM1[x] = new TH1F("","",800,300,1100);
  h_JpsiDphiM1[x] = new TH1F("","",250,-5,5);
  h_JpsiDrM1[x] = new TH1F("","",240,0,8);
  h_JpsiDistM2[x] = new TH1F("","",800,300,1100);
  h_JpsiDphiM2[x] = new TH1F("","",250,-5,5);
  h_JpsiDrM2[x] = new TH1F("","",240,0,8);
  
  h_jpsi_x[x] = new TH1F("JPsi X","",80,-20,20);
  h_jpsi_y[x] = new TH1F("JPsi Y","",60,-15,15);
  h_jpsi_z[x] = new TH1F("JPsi Z","",60,-15,15);
  h_jpsi_px[x] = new TH1F("JPsi P_{x}","",100,0,20);
  h_jpsi_py[x] = new TH1F("JPsi P_{y}","",100,0,20);
  h_jpsi_pz[x] = new TH1F("JPsi P_{z}","",75,0,15);
  h_jpsi_t[x] = new TH1F("JPsi T","",200,0,25);
  h_jpsi_Energy[x] = new TH1F("JPsi Energy","",120,0,30);
  h_jpsi_theta[x] = new TH1F("JPsi Theta","",120,0,3.1);
  h_jpsi_costheta[x] = new TH1F("JPsi Costheta","",30,0,1);
  h_jpsi_phi[x] = new TH1F("JPsi Phi","",50,0,3.3);
  h_jpsi_rho[x] = new TH1F("JPsi Rho","",75,0,30);
  h_jpsi_perp2[x] = new TH1F("JPsi Perp2","",500,0,500);
  h_jpsi_pt[x] = new TH1F("JPsi p_{T}","",90,0,30);
  h_jpsi_perp[x] = new TH1F("JPsi Perp","",100,0,50);
  h_jpsi_et2[x] = new TH1F("JPsi E_{T}^{2}","",100,0,300);
  h_jpsi_et[x] = new TH1F("JPsi E_{T}","",90,0,30);
  h_jpsi_Mag2[x] = new TH1F("JPsi Mag^{2}","",160,6,14);
  h_jpsi_Mag[x] = new TH1F("JPsi Mag","",120,2.5,3.5);
  h_jpsi_M[x] = new TH1F("JPsi M","",300,2.7,3.4);
  h_jpsi_Mt2[x] = new TH1F("JPsi Mt^{2}","",500,0,500);
  h_jpsi_Mt[x] = new TH1F("JPsi Mt","",180,0,30);
  h_jpsi_beta[x] = new TH1F("JPsi beta","",100,0.8,1.1);
  h_jpsi_gamma[x] = new TH1F("JPsi gamma","",120,0,15);
  h_jpsi_plus[x] = new TH1F("JPsi Plus","",50,0,50);
  h_jpsi_minus[x] = new TH1F("JPsi Minus","",40,0,40);
  h_jpsi_Rap[x] = new TH1F("JPsi Rap","",60,-1.6,1.6);
  h_jpsi_eta[x] = new TH1F("JPsi eta","",60,-1,1);
  h_jpsi_psuedorap[x] = new TH1F("JPsi Psuedorap","",96,-2,2);
  
  h_muplus_x[x] = new TH1F("muplus X","",80,-20,20);
  h_muplus_y[x] = new TH1F("muplus Y","",80,-20,20);
  h_muplus_z[x] = new TH1F("muplus Z","",80,-20,20);
  h_muplus_px[x] = new TH1F("muplus P_{x}","",75,0,15);
  h_muplus_py[x] = new TH1F("muplus P_{y}","",75,0,15);
  h_muplus_pz[x] = new TH1F("muplus P_{z}","",75,0,15);
  h_muplus_t[x] = new TH1F("muplus T","",200,0,25);
  h_muplus_Energy[x] = new TH1F("muplus Energy","",120,0,30);
  h_muplus_theta[x] = new TH1F("muplus Theta","",120,0,3.1);
  h_muplus_costheta[x] = new TH1F("muplus Costheta","",50,0,1);
  h_muplus_phi[x] = new TH1F("muplus Phi","",50,0,3.3);
  h_muplus_rho[x] = new TH1F("muplus Rho","",75,0,30);
  h_muplus_perp2[x] = new TH1F("muplus Perp2","",200,0,200);
  h_muplus_pt[x] = new TH1F("muplus p_{T}","",100,0,15);
  h_muplus_perp[x] = new TH1F("muplus Perp","",100,0,15);
  h_muplus_et2[x] = new TH1F("muplus E_{T}^{2}","",300,0,300);
  h_muplus_et[x] = new TH1F("muplus E_{T}","",90,0,30);
//  h_muplus_Mag2[x] = new TH1F("muplus Mag^{2}","",100,0,0.5);
//  h_muplus_Mag[x] = new TH1F("muplus Mag","",100,0,0.5);
//  h_muplus_M[x] = new TH1F("muplus M","",150,0,4);
  h_muplus_Mt2[x] = new TH1F("muplus Mt^{2}","",200,0,200);
  h_muplus_Mt[x] = new TH1F("muplus Mt","",40,0,20);
  h_muplus_beta[x] = new TH1F("muplus beta","",500,0.999,1.001);
  h_muplus_gamma[x] = new TH1F("muplus gamma","",160,25,100);
  h_muplus_plus[x] = new TH1F("muplus Plus","",80,0,40);
  h_muplus_minus[x] = new TH1F("muplus Minus","",40,0,40);
  h_muplus_Rap[x] = new TH1F("muplus Rap","",60,-1.6,1.6);
  h_muplus_eta[x] = new TH1F("muplus eta","",90,0,3.1);
  h_muplus_psuedorap[x] = new TH1F("muplus Psuedorap","",80,-3,3);
  
  h_muminus_x[x] = new TH1F("muminus X","",80,-20,20);
  h_muminus_y[x] = new TH1F("muminus Y","",80,-20,20);
  h_muminus_z[x] = new TH1F("muminus Z","",80,-20,20);
  h_muminus_px[x] = new TH1F("muminus P_{x}","",75,0,15);
  h_muminus_py[x] = new TH1F("muminus P_{y}","",75,0,15);
  h_muminus_pz[x] = new TH1F("muminus P_{z}","",75,0,15);
  h_muminus_t[x] = new TH1F("muminus T","",200,0,25);
  h_muminus_Energy[x] = new TH1F("muminus Energy","",120,0,30);
  h_muminus_theta[x] = new TH1F("muminus Theta","",120,0,3.1);
  h_muminus_costheta[x] = new TH1F("muminus Costheta","",50,0,1);
  h_muminus_phi[x] = new TH1F("muminus Phi","",50,0,3.3);
  h_muminus_rho[x] = new TH1F("muminus Rho","",75,0,30);
  h_muminus_perp2[x] = new TH1F("muminus Perp2","",200,0,200);
  h_muminus_pt[x] = new TH1F("muminus p_{T}","",100,0,15);
  h_muminus_perp[x] = new TH1F("muminus Perp","",100,0,15);
  h_muminus_et2[x] = new TH1F("muminus E_{T}^{2}","",300,0,300);
  h_muminus_et[x] = new TH1F("muminus E_{T}","",90,0,30);
//  h_muminus_Mag2[x] = new TH1F("muminus Mag^{2}","",100,0,0.5);
//  h_muminus_Mag[x] = new TH1F("muminus Mag","",100,0,0.5);
//  h_muminus_M[x] = new TH1F("muminus M","",150,0,4);
  h_muminus_Mt2[x] = new TH1F("muminus Mt^{2}","",200,0,200);
  h_muminus_Mt[x] = new TH1F("muminus Mt","",40,0,20);
  h_muminus_beta[x] = new TH1F("muminus beta","",500,0.999,1.001);
  h_muminus_gamma[x] = new TH1F("muminus gamma","",160,25,100);
  h_muminus_plus[x] = new TH1F("muminus Plus","",80,0,40);
  h_muminus_minus[x] = new TH1F("muminus Minus","",40,0,40);
  h_muminus_Rap[x] = new TH1F("muminus Rap","",60,-1.6,1.6);
  h_muminus_eta[x] = new TH1F("muminus eta","",90,0,3.1);
  h_muminus_psuedorap[x] = new TH1F("muminus Psuedorap","",80,-3,3);
  

  
  }

bool rejectCowboys = true;



   gStyle->SetOptStat(0);
   
   Long64_t nentries;
TFile *f[2];
   
//TTree *tree

   Long64_t nbytes = 0, nb = 0;
   
//   for(int rejCows = 0; rejCows < 2; rejCows++)
//   {
  // 	 if (rejCows == 0) rejectCowboys=false;
   	// if (rejCows == 1) rejectCowboys=true;
   	
   	bool useData2011;
   	
   for(int data2011 = 0; data2011 < 2; data2011++)
   {
   	 if (data2011 == 0) useData2011=false;
   	 if (data2011 == 1) useData2011=true;
cout<<"file is "<<data2011<<endl;
 	if(useData2011) 
  		f[data2011] = TFile::Open("/data/users/ferraioc/TTree_Onia2MuMu_v30_PromptRecoAB_10May2012_Jpsi.root");
  		
  		
  	if(!useData2011)
  		f[data2011] = TFile::Open("/data/users/ferraioc/Polarization/2012ppOniaData/r2012A_DoubMu_jpsi_v8.root");

  f[data2011]->cd();
  
  		f[data2011]->GetObject("data",fChain);

  onia = 0;
  muNeg = 0;
  muPos = 0;

{
  fChain->SetBranchAddress("JpsiP", &onia);
  fChain->SetBranchAddress("muNegP", &muNeg);
  fChain->SetBranchAddress("muPosP", &muPos);
  fChain->SetBranchAddress("eventNb", &eventNb);
  fChain->SetBranchAddress("runNb", &runNb);
  fChain->SetBranchAddress("lumiBlock", &lumiBlock);
  fChain->SetBranchAddress("nPriVtx", &nPriVtx);
  fChain->SetBranchAddress("vertexWeight", &vertexWeight);
  fChain->SetBranchAddress("Jpsict", &Jpsict);
  fChain->SetBranchAddress("JpsictErr", &JpsictErr);
  fChain->SetBranchAddress("sumPTPV", &sumPTPV);
  fChain->SetBranchAddress("JpsiMuScleMassCorr", &JpsiMuScleMassCorr);
  fChain->SetBranchAddress("countTksOfPV", &countTksOfPV);
  fChain->SetBranchAddress("JpsiMuScleMassErr", &JpsiMuScleMassErr);
  fChain->SetBranchAddress("sigmaPtPos", &sigmaPtPos);
  fChain->SetBranchAddress("sigmaPtNeg", &sigmaPtNeg);
  fChain->SetBranchAddress("JpsiMassErr", &JpsiMassErr);
  fChain->SetBranchAddress("JpsiVprob", &JpsiVprob);
  fChain->SetBranchAddress("JpsiDistM1", &JpsiDistM1);
  fChain->SetBranchAddress("JpsiDphiM1", &JpsiDphiM1);
  fChain->SetBranchAddress("JpsiDrM1", &JpsiDrM1);
  fChain->SetBranchAddress("JpsiDistM2", &JpsiDistM2);
  fChain->SetBranchAddress("JpsiDphiM2", &JpsiDphiM2);
  fChain->SetBranchAddress("JpsiDrM2", &JpsiDrM2);
  fChain->SetBranchAddress("HLT_Dimuon8_Jpsi_v3", &HLT_Dimuon8_Jpsi_v3);
  fChain->SetBranchAddress("HLT_Dimuon8_Jpsi_v4", &HLT_Dimuon8_Jpsi_v4);
  fChain->SetBranchAddress("HLT_Dimuon8_Jpsi_v5", &HLT_Dimuon8_Jpsi_v5);
  fChain->SetBranchAddress("HLT_Dimuon8_Jpsi_v6", &HLT_Dimuon8_Jpsi_v6);
  fChain->SetBranchAddress("HLT_Dimuon8_Jpsi_v7", &HLT_Dimuon8_Jpsi_v7);
  fChain->SetBranchAddress("HLT_Dimuon10_Jpsi_v3", &HLT_Dimuon10_Jpsi_v3);
  fChain->SetBranchAddress("HLT_Dimuon10_Jpsi_v4", &HLT_Dimuon10_Jpsi_v4);
  fChain->SetBranchAddress("HLT_Dimuon10_Jpsi_v5", &HLT_Dimuon10_Jpsi_v5);
  fChain->SetBranchAddress("HLT_Dimuon10_Jpsi_v6", &HLT_Dimuon10_Jpsi_v6);
  fChain->SetBranchAddress("HLT_Dimuon10_Jpsi_Barrel_v1", &HLT_Dimuon10_Jpsi_Barrel_v1);
  fChain->SetBranchAddress("HLT_Dimuon10_Jpsi_Barrel_v2", &HLT_Dimuon10_Jpsi_Barrel_v2);
  fChain->SetBranchAddress("HLT_Dimuon10_Jpsi_Barrel_v3", &HLT_Dimuon10_Jpsi_Barrel_v3);
  fChain->SetBranchAddress("HLT_Dimuon10_Jpsi_Barrel_v5", &HLT_Dimuon10_Jpsi_Barrel_v5);
  fChain->SetBranchAddress("HLT_Dimuon10_Jpsi_Barrel_v6", &HLT_Dimuon10_Jpsi_Barrel_v6);
  fChain->SetBranchAddress("HLT_Dimuon10_Jpsi_Barrel_v7", &HLT_Dimuon10_Jpsi_Barrel_v7);
  fChain->SetBranchAddress("HLT_Dimuon8_Jpsi_v3", &HLT_Dimuon8_Jpsi_v3);
  fChain->SetBranchAddress("HLT_Dimuon8_Jpsi_v4", &HLT_Dimuon8_Jpsi_v4);
  fChain->SetBranchAddress("HLT_Dimuon8_Jpsi_v5", &HLT_Dimuon8_Jpsi_v5);
  fChain->SetBranchAddress("HLT_Dimuon10_Jpsi_v3", &HLT_Dimuon10_Jpsi_v3);
  fChain->SetBranchAddress("HLT_Dimuon10_Jpsi_v4", &HLT_Dimuon10_Jpsi_v4);
}

Long64_t nentries = fChain->GetEntriesFast();
	std::cout << "File "<<data2011<<"; number of entries = " << nentries << std::endl;
	nentries = 5416828;
//	nentries = 10000;
   for (Long64_t jentry=0; jentry<nentries;jentry++) {
   fChain->GetEntry(jentry);

	if(jentry % 10000 == 0) std::cout << "event " << jentry << " of " << nentries << std::endl;

   int trigDecision = -99;
	if( HLT_Dimuon8_Jpsi_v3 == 1  ||     // 2012
            HLT_Dimuon8_Jpsi_v4 == 1  || // 2012
            HLT_Dimuon8_Jpsi_v5 == 1  || // 2012
            HLT_Dimuon8_Jpsi_v6 == 1  || // 2012
            HLT_Dimuon8_Jpsi_v7 == 1  || // 2012
            HLT_Dimuon10_Jpsi_v3 == 1 || // 2012
            HLT_Dimuon10_Jpsi_v4 == 1 || // 2012
            HLT_Dimuon10_Jpsi_v5 == 1 || // 2012
            HLT_Dimuon10_Jpsi_v6 == 1 || // 2012
            HLT_Dimuon10_Jpsi_Barrel_v1 == 1 || // 2011
            HLT_Dimuon10_Jpsi_Barrel_v2 == 1 || // 2011
            HLT_Dimuon10_Jpsi_Barrel_v3 == 1 || // 2011
            HLT_Dimuon10_Jpsi_Barrel_v5 == 1 || // 2011
            HLT_Dimuon10_Jpsi_Barrel_v6 == 1 || // 2011
            HLT_Dimuon10_Jpsi_Barrel_v7 == 1 || // 2011
            HLT_Dimuon8_Jpsi_v3 == 1  || // 2011
			HLT_Dimuon8_Jpsi_v4 == 1  || // 2011
			HLT_Dimuon8_Jpsi_v5 == 1  || // 2011
			HLT_Dimuon10_Jpsi_v3 == 1 || // 2011
			HLT_Dimuon10_Jpsi_v4 == 1
			)
          trigDecision = 1;

	if(trigDecision != 1 ) continue;
    if(onia->Pt() < 10. || onia->Pt() > 15.) continue;

    if(onia->Rapidity() > 0.5. || onia->Rapidity() < -0.5.) continue;


	double deltaPhi = muNeg->Phi() - muPos->Phi();
	if(deltaPhi > TMath::Pi()) deltaPhi -= 2.*TMath::Pi();
	else if(deltaPhi < -TMath::Pi()) deltaPhi += 2.*TMath::Pi();

	if(rejectCowboys){
	if(deltaPhi < 0.)  continue;
	}
  h_nPriVtx[data2011]->Fill(nPriVtx);
  h_vertexWeight[data2011]->Fill(vertexWeight);
  h_sumPTPV[data2011]->Fill(sumPTPV);
  h_countTksOfPV[data2011]->Fill(countTksOfPV);
//  h_JpsiMuScleMassCorr[data2011]->Fill(JpsiMuScleMassCorr);
//  h_JpsiMuScleMassErr[data2011]->Fill(JpsiMuScleMassErr);
  h_JpsiMassErr[data2011]->Fill(JpsiMassErr);
//  h_sigmaPtPos[data2011]->Fill(sigmaPtPos);
//  h_sigmaPtNeg[data2011]->Fill(sigmaPtNeg);
  h_Jpsict[data2011]->Fill(Jpsict);
  h_JpsictErr[data2011]->Fill(JpsictErr);
  h_JpsiVprob[data2011]->Fill(JpsiVprob);
  h_JpsiDistM1[data2011]->Fill(JpsiDistM1);
  h_JpsiDphiM1[data2011]->Fill(JpsiDphiM1);
  h_JpsiDrM1[data2011]->Fill(JpsiDrM1);
  h_JpsiDistM2[data2011]->Fill(JpsiDistM2);
  h_JpsiDphiM2[data2011]->Fill(JpsiDphiM2);
  h_JpsiDrM2[data2011]->Fill(JpsiDrM2);
  
   h_jpsi_x[data2011]->Fill(onia->X());
  h_jpsi_y[data2011]->Fill(onia->Y());
  h_jpsi_z[data2011]->Fill(onia->Z());
  h_jpsi_px[data2011]->Fill(onia->Px());
  h_jpsi_py[data2011]->Fill(onia->Py());
  h_jpsi_pz[data2011]->Fill(onia->Pz());
  h_jpsi_t[data2011]->Fill(onia->T());
  h_jpsi_Energy[data2011]->Fill(onia->Energy());
  h_jpsi_theta[data2011]->Fill(onia->Theta());
  h_jpsi_costheta[data2011]->Fill(onia->CosTheta());
  h_jpsi_phi[data2011]->Fill(onia->Phi());
  h_jpsi_rho[data2011]->Fill(onia->Rho());
  h_jpsi_perp2[data2011]->Fill(onia->Perp2());
  h_jpsi_pt[data2011]->Fill(onia->Pt());
  h_jpsi_perp[data2011]->Fill(onia->Perp());
  h_jpsi_et2[data2011]->Fill(onia->Et2());
  h_jpsi_et[data2011]->Fill(onia->Et());
  h_jpsi_Mag2[data2011]->Fill(onia->Mag2());
  h_jpsi_Mag[data2011]->Fill(onia->Mag());
  h_jpsi_M[data2011]->Fill(onia->M());
  h_jpsi_Mt2[data2011]->Fill(onia->Mt2());
  h_jpsi_Mt[data2011]->Fill(onia->Mt());
  h_jpsi_beta[data2011]->Fill(onia->Beta());
  h_jpsi_gamma[data2011]->Fill(onia->Gamma());
  h_jpsi_plus[data2011]->Fill(onia->Plus());
  h_jpsi_minus[data2011]->Fill(onia->Minus());
  h_jpsi_Rap[data2011]->Fill(onia->Rapidity());
  h_jpsi_eta[data2011]->Fill(onia->Eta());
  h_jpsi_psuedorap[data2011]->Fill(onia->PseudoRapidity());
  
     h_muplus_x[data2011]->Fill(muPos->X());
  h_muplus_y[data2011]->Fill(muPos->Y());
  h_muplus_z[data2011]->Fill(muPos->Z());
  h_muplus_px[data2011]->Fill(muPos->Px());
  h_muplus_py[data2011]->Fill(muPos->Py());
  h_muplus_pz[data2011]->Fill(muPos->Pz());
  h_muplus_t[data2011]->Fill(muPos->T());
  h_muplus_Energy[data2011]->Fill(muPos->Energy());
  h_muplus_theta[data2011]->Fill(muPos->Theta());
  h_muplus_costheta[data2011]->Fill(muPos->CosTheta());
  h_muplus_phi[data2011]->Fill(muPos->Phi());
  h_muplus_rho[data2011]->Fill(muPos->Rho());
  h_muplus_perp2[data2011]->Fill(muPos->Perp2());
  h_muplus_pt[data2011]->Fill(muPos->Pt());
  h_muplus_perp[data2011]->Fill(muPos->Perp());
  h_muplus_et2[data2011]->Fill(muPos->Et2());
  h_muplus_et[data2011]->Fill(muPos->Et());
//  h_muplus_Mag2[data2011]->Fill(muPos->Mag2());
//  h_muplus_Mag[data2011]->Fill(muPos->Mag());
//  h_muplus_M[data2011]->Fill(muPos->M());
  h_muplus_Mt2[data2011]->Fill(muPos->Mt2());
  h_muplus_Mt[data2011]->Fill(muPos->Mt());
  h_muplus_beta[data2011]->Fill(muPos->Beta());
  h_muplus_gamma[data2011]->Fill(muPos->Gamma());
  h_muplus_plus[data2011]->Fill(muPos->Plus());
  h_muplus_minus[data2011]->Fill(muPos->Minus());
  h_muplus_Rap[data2011]->Fill(muPos->Rapidity());
  h_muplus_eta[data2011]->Fill(muPos->Eta());
  h_muplus_psuedorap[data2011]->Fill(muPos->PseudoRapidity());
  
     h_muminus_x[data2011]->Fill(muNeg->X());
  h_muminus_y[data2011]->Fill(muNeg->Y());
  h_muminus_z[data2011]->Fill(muNeg->Z());
  h_muminus_px[data2011]->Fill(muNeg->Px());
  h_muminus_py[data2011]->Fill(muNeg->Py());
  h_muminus_pz[data2011]->Fill(muNeg->Pz());
  h_muminus_t[data2011]->Fill(muNeg->T());
  h_muminus_Energy[data2011]->Fill(muNeg->Energy());
  h_muminus_theta[data2011]->Fill(muNeg->Theta());
  h_muminus_costheta[data2011]->Fill(muNeg->CosTheta());
  h_muminus_phi[data2011]->Fill(muNeg->Phi());
  h_muminus_rho[data2011]->Fill(muNeg->Rho());
  h_muminus_perp2[data2011]->Fill(muNeg->Perp2());
  h_muminus_pt[data2011]->Fill(muNeg->Pt());
  h_muminus_perp[data2011]->Fill(muNeg->Perp());
  h_muminus_et2[data2011]->Fill(muNeg->Et2());
  h_muminus_et[data2011]->Fill(muNeg->Et());
//  h_muminus_Mag2[data2011]->Fill(muNeg->Mag2());
//  h_muminus_Mag[data2011]->Fill(muNeg->Mag());
//  h_muminus_M[data2011]->Fill(muNeg->M());
  h_muminus_Mt2[data2011]->Fill(muNeg->Mt2());
  h_muminus_Mt[data2011]->Fill(muNeg->Mt());
  h_muminus_beta[data2011]->Fill(muNeg->Beta());
  h_muminus_gamma[data2011]->Fill(muNeg->Gamma());
  h_muminus_plus[data2011]->Fill(muNeg->Plus());
  h_muminus_minus[data2011]->Fill(muNeg->Minus());
  h_muminus_Rap[data2011]->Fill(muNeg->Rapidity());
  h_muminus_eta[data2011]->Fill(muNeg->Eta());
  h_muminus_psuedorap[data2011]->Fill(muNeg->PseudoRapidity());
  
  
}

}

   char pdfname[200];
   
   Double_t norm; 
for(int data2011 = 0; data2011 < 2; data2011++)
   {
   		norm = h_nPriVtx[data2011]->GetEntries();
   		h_nPriVtx[data2011]->Scale(1/norm);
   		h_nPriVtx[data2011]->SetLineColor(data2011+1);
   		
   		norm = h_vertexWeight[data2011]->GetEntries();
   		h_vertexWeight[data2011]->Scale(1/norm);
   		h_vertexWeight[data2011]->SetLineColor(data2011+1);
   		
   		norm = h_sumPTPV[data2011]->GetEntries();
   		h_sumPTPV[data2011]->Scale(1/norm);
   		h_sumPTPV[data2011]->SetLineColor(data2011+1);
   		
   		norm = h_countTksOfPV[data2011]->GetEntries();
   		h_countTksOfPV[data2011]->Scale(1/norm);
   		h_countTksOfPV[data2011]->SetLineColor(data2011+1);
   		
//   		norm = h_JpsiMuScleMassCorr[data2011]->GetEntries();
  // 		h_JpsiMuScleMassCorr[data2011]->Scale(1/norm);
   	//	h_JpsiMuScleMassCorr[data2011]->SetLineColor(data2011+1);
   		
//   		norm = h_JpsiMuScleMassErr[data2011]->GetEntries();
  // 		h_JpsiMuScleMassErr[data2011]->Scale(1/norm);
   	//	h_JpsiMuScleMassErr[data2011]->SetLineColor(data2011+1);
   		
//   		norm = h_sigmaPtPos[data2011]->GetEntries();
//   		h_sigmaPtPos[data2011]->Scale(1/norm);
//   		h_sigmaPtPos[data2011]->SetLineColor(data2011+1);
   		
//   		norm = h_sigmaPtNeg[data2011]->GetEntries();
//   		h_sigmaPtNeg[data2011]->Scale(1/norm);
//   		h_sigmaPtNeg[data2011]->SetLineColor(data2011+1);
   		
   		norm = h_Jpsict[data2011]->GetEntries();
   		h_Jpsict[data2011]->Scale(1/norm);
   		h_Jpsict[data2011]->SetLineColor(data2011+1);
   		
   		norm = h_JpsictErr[data2011]->GetEntries();
   		h_JpsictErr[data2011]->Scale(1/norm);
   		h_JpsictErr[data2011]->SetLineColor(data2011+1);
   		
   		norm = h_JpsiVprob[data2011]->GetEntries();
   		h_JpsiVprob[data2011]->Scale(1/norm);
   		h_JpsiVprob[data2011]->SetLineColor(data2011+1);
   		
   		norm = h_JpsiDistM1[data2011]->GetEntries();
   		h_JpsiDistM1[data2011]->Scale(1/norm);
   		h_JpsiDistM1[data2011]->SetLineColor(data2011+1);
   		
   		norm = h_JpsiDphiM1[data2011]->GetEntries();
   		h_JpsiDphiM1[data2011]->Scale(1/norm);
   		h_JpsiDphiM1[data2011]->SetLineColor(data2011+1);
   		
   		norm = h_JpsiDrM1[data2011]->GetEntries();
   		h_JpsiDrM1[data2011]->Scale(1/norm);
   		h_JpsiDrM1[data2011]->SetLineColor(data2011+1);
   		
   		norm = h_JpsiDistM2[data2011]->GetEntries();
   		h_JpsiDistM2[data2011]->Scale(1/norm);
   		h_JpsiDistM2[data2011]->SetLineColor(data2011+1);
   		
   		norm = h_JpsiDphiM2[data2011]->GetEntries();
   		h_JpsiDphiM2[data2011]->Scale(1/norm);
   		h_JpsiDphiM2[data2011]->SetLineColor(data2011+1);
   		
   		norm = h_JpsiDrM2[data2011]->GetEntries();
   		h_JpsiDrM2[data2011]->Scale(1/norm);
   		h_JpsiDrM2[data2011]->SetLineColor(data2011+1);
   		
   		norm = h_JpsiMassErr[data2011]->GetEntries();
   		h_JpsiMassErr[data2011]->Scale(1/norm);
   		h_JpsiMassErr[data2011]->SetLineColor(data2011+1);
   		
   		h_muminus_x[data2011]->GetEntries();
		h_muminus_x[data2011]->Scale(1/norm);
		h_muminus_x[data2011]->SetLineColor(data2011+1);
		h_muminus_y[data2011]->GetEntries();
		h_muminus_y[data2011]->Scale(1/norm);
		h_muminus_y[data2011]->SetLineColor(data2011+1);
		h_muminus_z[data2011]->GetEntries();
		h_muminus_z[data2011]->Scale(1/norm);
		h_muminus_z[data2011]->SetLineColor(data2011+1);
		h_muminus_px[data2011]->GetEntries();
		h_muminus_px[data2011]->Scale(1/norm);
		h_muminus_px[data2011]->SetLineColor(data2011+1);
		h_muminus_py[data2011]->GetEntries();
		h_muminus_py[data2011]->Scale(1/norm);
		h_muminus_py[data2011]->SetLineColor(data2011+1);
		h_muminus_pz[data2011]->GetEntries();
		h_muminus_pz[data2011]->Scale(1/norm);
		h_muminus_pz[data2011]->SetLineColor(data2011+1);
		h_muminus_t[data2011]->GetEntries();
		h_muminus_t[data2011]->Scale(1/norm);
		h_muminus_t[data2011]->SetLineColor(data2011+1);
		h_muminus_Energy[data2011]->GetEntries();
		h_muminus_Energy[data2011]->Scale(1/norm);
		h_muminus_Energy[data2011]->SetLineColor(data2011+1);
		h_muminus_theta[data2011]->GetEntries();
		h_muminus_theta[data2011]->Scale(1/norm);
		h_muminus_theta[data2011]->SetLineColor(data2011+1);
		h_muminus_costheta[data2011]->GetEntries();
		h_muminus_costheta[data2011]->Scale(1/norm);
		h_muminus_costheta[data2011]->SetLineColor(data2011+1);
		h_muminus_phi[data2011]->GetEntries();
		h_muminus_phi[data2011]->Scale(1/norm);
		h_muminus_phi[data2011]->SetLineColor(data2011+1);
		h_muminus_rho[data2011]->GetEntries();
		h_muminus_rho[data2011]->Scale(1/norm);
		h_muminus_rho[data2011]->SetLineColor(data2011+1);
		h_muminus_perp2[data2011]->GetEntries();
		h_muminus_perp2[data2011]->Scale(1/norm);
		h_muminus_perp2[data2011]->SetLineColor(data2011+1);
		h_muminus_pt[data2011]->GetEntries();
		h_muminus_pt[data2011]->Scale(1/norm);
		h_muminus_pt[data2011]->SetLineColor(data2011+1);
		h_muminus_perp[data2011]->GetEntries();
		h_muminus_perp[data2011]->Scale(1/norm);
		h_muminus_perp[data2011]->SetLineColor(data2011+1);
		h_muminus_et2[data2011]->GetEntries();
		h_muminus_et2[data2011]->Scale(1/norm);
		h_muminus_et2[data2011]->SetLineColor(data2011+1);
		h_muminus_et[data2011]->GetEntries();
		h_muminus_et[data2011]->Scale(1/norm);
		h_muminus_et[data2011]->SetLineColor(data2011+1);
//		h_muminus_Mag2[data2011]->GetEntries();
//		h_muminus_Mag2[data2011]->Scale(1/norm);
//		h_muminus_Mag2[data2011]->SetLineColor(data2011+1);
//		h_muminus_Mag[data2011]->GetEntries();
//		h_muminus_Mag[data2011]->Scale(1/norm);
//		h_muminus_Mag[data2011]->SetLineColor(data2011+1);
//		h_muminus_M[data2011]->GetEntries();
//		h_muminus_M[data2011]->Scale(1/norm);
//		h_muminus_M[data2011]->SetLineColor(data2011+1);
		h_muminus_Mt2[data2011]->GetEntries();
		h_muminus_Mt2[data2011]->Scale(1/norm);
		h_muminus_Mt2[data2011]->SetLineColor(data2011+1);
		h_muminus_Mt[data2011]->GetEntries();
		h_muminus_Mt[data2011]->Scale(1/norm);
		h_muminus_Mt[data2011]->SetLineColor(data2011+1);
		h_muminus_beta[data2011]->GetEntries();
		h_muminus_beta[data2011]->Scale(1/norm);
		h_muminus_beta[data2011]->SetLineColor(data2011+1);
		h_muminus_gamma[data2011]->GetEntries();
		h_muminus_gamma[data2011]->Scale(1/norm);
		h_muminus_gamma[data2011]->SetLineColor(data2011+1);
		h_muminus_plus[data2011]->GetEntries();
		h_muminus_plus[data2011]->Scale(1/norm);
		h_muminus_plus[data2011]->SetLineColor(data2011+1);
		h_muminus_minus[data2011]->GetEntries();
		h_muminus_minus[data2011]->Scale(1/norm);
		h_muminus_minus[data2011]->SetLineColor(data2011+1);
		h_muminus_Rap[data2011]->GetEntries();
		h_muminus_Rap[data2011]->Scale(1/norm);
		h_muminus_Rap[data2011]->SetLineColor(data2011+1);
		h_muminus_eta[data2011]->GetEntries();
		h_muminus_eta[data2011]->Scale(1/norm);
		h_muminus_eta[data2011]->SetLineColor(data2011+1);
		h_muminus_psuedorap[data2011]->GetEntries();
		h_muminus_psuedorap[data2011]->Scale(1/norm);
		h_muminus_psuedorap[data2011]->SetLineColor(data2011+1);
		
		h_muplus_x[data2011]->GetEntries();
		h_muplus_x[data2011]->Scale(1/norm);
		h_muplus_x[data2011]->SetLineColor(data2011+1);
		h_muplus_y[data2011]->GetEntries();
		h_muplus_y[data2011]->Scale(1/norm);
		h_muplus_y[data2011]->SetLineColor(data2011+1);
		h_muplus_z[data2011]->GetEntries();
		h_muplus_z[data2011]->Scale(1/norm);
		h_muplus_z[data2011]->SetLineColor(data2011+1);
		h_muplus_px[data2011]->GetEntries();
		h_muplus_px[data2011]->Scale(1/norm);
		h_muplus_px[data2011]->SetLineColor(data2011+1);
		h_muplus_py[data2011]->GetEntries();
		h_muplus_py[data2011]->Scale(1/norm);
		h_muplus_py[data2011]->SetLineColor(data2011+1);
		h_muplus_pz[data2011]->GetEntries();
		h_muplus_pz[data2011]->Scale(1/norm);
		h_muplus_pz[data2011]->SetLineColor(data2011+1);
		h_muplus_t[data2011]->GetEntries();
		h_muplus_t[data2011]->Scale(1/norm);
		h_muplus_t[data2011]->SetLineColor(data2011+1);
		h_muplus_Energy[data2011]->GetEntries();
		h_muplus_Energy[data2011]->Scale(1/norm);
		h_muplus_Energy[data2011]->SetLineColor(data2011+1);
		h_muplus_theta[data2011]->GetEntries();
		h_muplus_theta[data2011]->Scale(1/norm);
		h_muplus_theta[data2011]->SetLineColor(data2011+1);
		h_muplus_costheta[data2011]->GetEntries();
		h_muplus_costheta[data2011]->Scale(1/norm);
		h_muplus_costheta[data2011]->SetLineColor(data2011+1);
		h_muplus_phi[data2011]->GetEntries();
		h_muplus_phi[data2011]->Scale(1/norm);
		h_muplus_phi[data2011]->SetLineColor(data2011+1);
		h_muplus_rho[data2011]->GetEntries();
		h_muplus_rho[data2011]->Scale(1/norm);
		h_muplus_rho[data2011]->SetLineColor(data2011+1);
		h_muplus_perp2[data2011]->GetEntries();
		h_muplus_perp2[data2011]->Scale(1/norm);
		h_muplus_perp2[data2011]->SetLineColor(data2011+1);
		h_muplus_pt[data2011]->GetEntries();
		h_muplus_pt[data2011]->Scale(1/norm);
		h_muplus_pt[data2011]->SetLineColor(data2011+1);
		h_muplus_perp[data2011]->GetEntries();
		h_muplus_perp[data2011]->Scale(1/norm);
		h_muplus_perp[data2011]->SetLineColor(data2011+1);
		h_muplus_et2[data2011]->GetEntries();
		h_muplus_et2[data2011]->Scale(1/norm);
		h_muplus_et2[data2011]->SetLineColor(data2011+1);
		h_muplus_et[data2011]->GetEntries();
		h_muplus_et[data2011]->Scale(1/norm);
		h_muplus_et[data2011]->SetLineColor(data2011+1);
//		h_muplus_Mag2[data2011]->GetEntries();
//		h_muplus_Mag2[data2011]->Scale(1/norm);
//		h_muplus_Mag2[data2011]->SetLineColor(data2011+1);
//		h_muplus_Mag[data2011]->GetEntries();
//		h_muplus_Mag[data2011]->Scale(1/norm);
//		h_muplus_Mag[data2011]->SetLineColor(data2011+1);
//		h_muplus_M[data2011]->GetEntries();
//		h_muplus_M[data2011]->Scale(1/norm);
//		h_muplus_M[data2011]->SetLineColor(data2011+1);
		h_muplus_Mt2[data2011]->GetEntries();
		h_muplus_Mt2[data2011]->Scale(1/norm);
		h_muplus_Mt2[data2011]->SetLineColor(data2011+1);
		h_muplus_Mt[data2011]->GetEntries();
		h_muplus_Mt[data2011]->Scale(1/norm);
		h_muplus_Mt[data2011]->SetLineColor(data2011+1);
		h_muplus_beta[data2011]->GetEntries();
		h_muplus_beta[data2011]->Scale(1/norm);
		h_muplus_beta[data2011]->SetLineColor(data2011+1);
		h_muplus_gamma[data2011]->GetEntries();
		h_muplus_gamma[data2011]->Scale(1/norm);
		h_muplus_gamma[data2011]->SetLineColor(data2011+1);
		h_muplus_plus[data2011]->GetEntries();
		h_muplus_plus[data2011]->Scale(1/norm);
		h_muplus_plus[data2011]->SetLineColor(data2011+1);
		h_muplus_minus[data2011]->GetEntries();
		h_muplus_minus[data2011]->Scale(1/norm);
		h_muplus_minus[data2011]->SetLineColor(data2011+1);
		h_muplus_Rap[data2011]->GetEntries();
		h_muplus_Rap[data2011]->Scale(1/norm);
		h_muplus_Rap[data2011]->SetLineColor(data2011+1);
		h_muplus_eta[data2011]->GetEntries();
		h_muplus_eta[data2011]->Scale(1/norm);
		h_muplus_eta[data2011]->SetLineColor(data2011+1);
		h_muplus_psuedorap[data2011]->GetEntries();
		h_muplus_psuedorap[data2011]->Scale(1/norm);
		h_muplus_psuedorap[data2011]->SetLineColor(data2011+1);
		
		h_jpsi_x[data2011]->GetEntries();
		h_jpsi_x[data2011]->Scale(1/norm);
		h_jpsi_x[data2011]->SetLineColor(data2011+1);
		h_jpsi_y[data2011]->GetEntries();
		h_jpsi_y[data2011]->Scale(1/norm);
		h_jpsi_y[data2011]->SetLineColor(data2011+1);
		h_jpsi_z[data2011]->GetEntries();
		h_jpsi_z[data2011]->Scale(1/norm);
		h_jpsi_z[data2011]->SetLineColor(data2011+1);
		h_jpsi_px[data2011]->GetEntries();
		h_jpsi_px[data2011]->Scale(1/norm);
		h_jpsi_px[data2011]->SetLineColor(data2011+1);
		h_jpsi_py[data2011]->GetEntries();
		h_jpsi_py[data2011]->Scale(1/norm);
		h_jpsi_py[data2011]->SetLineColor(data2011+1);
		h_jpsi_pz[data2011]->GetEntries();
		h_jpsi_pz[data2011]->Scale(1/norm);
		h_jpsi_pz[data2011]->SetLineColor(data2011+1);
		h_jpsi_t[data2011]->GetEntries();
		h_jpsi_t[data2011]->Scale(1/norm);
		h_jpsi_t[data2011]->SetLineColor(data2011+1);
		h_jpsi_Energy[data2011]->GetEntries();
		h_jpsi_Energy[data2011]->Scale(1/norm);
		h_jpsi_Energy[data2011]->SetLineColor(data2011+1);
		h_jpsi_theta[data2011]->GetEntries();
		h_jpsi_theta[data2011]->Scale(1/norm);
		h_jpsi_theta[data2011]->SetLineColor(data2011+1);
		h_jpsi_costheta[data2011]->GetEntries();
		h_jpsi_costheta[data2011]->Scale(1/norm);
		h_jpsi_costheta[data2011]->SetLineColor(data2011+1);
		h_jpsi_phi[data2011]->GetEntries();
		h_jpsi_phi[data2011]->Scale(1/norm);
		h_jpsi_phi[data2011]->SetLineColor(data2011+1);
		h_jpsi_rho[data2011]->GetEntries();
		h_jpsi_rho[data2011]->Scale(1/norm);
		h_jpsi_rho[data2011]->SetLineColor(data2011+1);
		h_jpsi_perp2[data2011]->GetEntries();
		h_jpsi_perp2[data2011]->Scale(1/norm);
		h_jpsi_perp2[data2011]->SetLineColor(data2011+1);
		h_jpsi_pt[data2011]->GetEntries();
		h_jpsi_pt[data2011]->Scale(1/norm);
		h_jpsi_pt[data2011]->SetLineColor(data2011+1);
		h_jpsi_perp[data2011]->GetEntries();
		h_jpsi_perp[data2011]->Scale(1/norm);
		h_jpsi_perp[data2011]->SetLineColor(data2011+1);
		h_jpsi_et2[data2011]->GetEntries();
		h_jpsi_et2[data2011]->Scale(1/norm);
		h_jpsi_et2[data2011]->SetLineColor(data2011+1);
		h_jpsi_et[data2011]->GetEntries();
		h_jpsi_et[data2011]->Scale(1/norm);
		h_jpsi_et[data2011]->SetLineColor(data2011+1);
		h_jpsi_Mag2[data2011]->GetEntries();
		h_jpsi_Mag2[data2011]->Scale(1/norm);
		h_jpsi_Mag2[data2011]->SetLineColor(data2011+1);
		h_jpsi_Mag[data2011]->GetEntries();
		h_jpsi_Mag[data2011]->Scale(1/norm);
		h_jpsi_Mag[data2011]->SetLineColor(data2011+1);
		h_jpsi_M[data2011]->GetEntries();
		h_jpsi_M[data2011]->Scale(1/norm);
		h_jpsi_M[data2011]->SetLineColor(data2011+1);
		h_jpsi_Mt2[data2011]->GetEntries();
		h_jpsi_Mt2[data2011]->Scale(1/norm);
		h_jpsi_Mt2[data2011]->SetLineColor(data2011+1);
		h_jpsi_Mt[data2011]->GetEntries();
		h_jpsi_Mt[data2011]->Scale(1/norm);
		h_jpsi_Mt[data2011]->SetLineColor(data2011+1);
		h_jpsi_beta[data2011]->GetEntries();
		h_jpsi_beta[data2011]->Scale(1/norm);
		h_jpsi_beta[data2011]->SetLineColor(data2011+1);
		h_jpsi_gamma[data2011]->GetEntries();
		h_jpsi_gamma[data2011]->Scale(1/norm);
		h_jpsi_gamma[data2011]->SetLineColor(data2011+1);
		h_jpsi_plus[data2011]->GetEntries();
		h_jpsi_plus[data2011]->Scale(1/norm);
		h_jpsi_plus[data2011]->SetLineColor(data2011+1);
		h_jpsi_minus[data2011]->GetEntries();
		h_jpsi_minus[data2011]->Scale(1/norm);
		h_jpsi_minus[data2011]->SetLineColor(data2011+1);
		h_jpsi_Rap[data2011]->GetEntries();
		h_jpsi_Rap[data2011]->Scale(1/norm);
		h_jpsi_Rap[data2011]->SetLineColor(data2011+1);
		h_jpsi_eta[data2011]->GetEntries();
		h_jpsi_eta[data2011]->Scale(1/norm);
		h_jpsi_eta[data2011]->SetLineColor(data2011+1);
		h_jpsi_psuedorap[data2011]->GetEntries();
		h_jpsi_psuedorap[data2011]->Scale(1/norm);
		h_jpsi_psuedorap[data2011]->SetLineColor(data2011+1);
   }
   
    leg = new TLegend(0.7,0.75,0.9,0.9);
    leg->AddEntry(h_JpsiMassErr[0],"2012 Data","f");
    leg->AddEntry(h_JpsiMassErr[1],"2011 Data","f");
    leg->SetFillStyle(0);
    gStyle->SetStatStyle(0); 
	gStyle->SetTitleStyle(0); 
	gROOT->ForceStyle();

    gStyle->SetFrameFillColor(-1);  
   
   
   for(int x = 0; x < 2; x++)
   {
  h_nPriVtx[x]->SetTitle("nPriVtx");
  h_vertexWeight[x]->SetTitle("vertexWeight");
  h_sumPTPV[x]->SetTitle("sumPTPV");
  h_countTksOfPV[x]->SetTitle("countTksOfPV");
//  h_JpsiMuScleMassCorr[x]->SetTitle("JpsiMuScleMassCorr");
//  h_JpsiMuScleMassErr[x]->SetTitle("JpsiMuScleMassErr");
  h_JpsiMassErr[x]->SetTitle("JpsiMassErr");
//  h_sigmaPtPos[x]->SetTitle("sigmaPtPos");
//  h_sigmaPtNeg[x]->SetTitle("sigmaPtNeg");
  h_Jpsict[x]->SetTitle("Jpsict");
  h_JpsictErr[x]->SetTitle("JpsictErr");
  h_JpsiVprob[x]->SetTitle("JpsiVprob");
  h_JpsiDistM1[x]->SetTitle("JpsiDistM1");
  h_JpsiDphiM1[x]->SetTitle("JpsiDphiM1");
  h_JpsiDrM1[x]->SetTitle("JpsiDrM1");
  h_JpsiDistM2[x]->SetTitle("JpsiDistM2");
  h_JpsiDphiM2[x]->SetTitle("JpsiDphiM2");
  h_JpsiDrM2[x]->SetTitle("JpsiDrM2");
h_muminus_x[x]->SetTitle("MuMinus X");
h_muminus_y[x]->SetTitle("MuMinus Y");
h_muminus_z[x]->SetTitle("MuMinus Z");
h_muminus_px[x]->SetTitle("MuMinus p_{X}");
h_muminus_py[x]->SetTitle("MuMinus p_{Y}");
h_muminus_pz[x]->SetTitle("MuMinus p_{Z}");
h_muminus_t[x]->SetTitle("MuMinus T");
h_muminus_Energy[x]->SetTitle("MuMinus Energy");
h_muminus_theta[x]->SetTitle("MuMinus Theta");
h_muminus_costheta[x]->SetTitle("MuMinus CosTheta");
h_muminus_phi[x]->SetTitle("MuMinus Phi");
h_muminus_rho[x]->SetTitle("MuMinus Rho");
h_muminus_perp2[x]->SetTitle("MuMinus Perp^{2}");
h_muminus_pt[x]->SetTitle("MuMinus p_{T}");
h_muminus_perp[x]->SetTitle("MuMinus Perp");
h_muminus_et2[x]->SetTitle("MuMinus E^{2}_{T}");
h_muminus_et[x]->SetTitle("MuMinus E_{T}");
//h_muminus_Mag2[x]->SetTitle("MuMinus Mag^{2}");
//h_muminus_Mag[x]->SetTitle("MuMinus Mag");
//h_muminus_M[x]->SetTitle("MuMinus M");
h_muminus_Mt2[x]->SetTitle("MuMinus Mt^{2}");
h_muminus_Mt[x]->SetTitle("MuMinus Mt");
h_muminus_beta[x]->SetTitle("MuMinus Beta");
h_muminus_gamma[x]->SetTitle("MuMinus Gamma");
h_muminus_plus[x]->SetTitle("MuMinus Plus");
h_muminus_minus[x]->SetTitle("MuMinus Minus");
h_muminus_Rap[x]->SetTitle("MuMinus Rap");
h_muminus_eta[x]->SetTitle("MuMinus Eta");
h_muminus_psuedorap[x]->SetTitle("MuMinus Psueodorap");

h_jpsi_x[x]->SetTitle("Jpsi X");
h_jpsi_y[x]->SetTitle("Jpsi Y");
h_jpsi_z[x]->SetTitle("Jpsi Z");
h_jpsi_px[x]->SetTitle("Jpsi p_{X}");
h_jpsi_py[x]->SetTitle("Jpsi p_{Y}");
h_jpsi_pz[x]->SetTitle("Jpsi p_{Z}");
h_jpsi_t[x]->SetTitle("Jpsi T");
h_jpsi_Energy[x]->SetTitle("Jpsi Energy");
h_jpsi_theta[x]->SetTitle("Jpsi Theta");
h_jpsi_costheta[x]->SetTitle("Jpsi CosTheta");
h_jpsi_phi[x]->SetTitle("Jpsi Phi");
h_jpsi_rho[x]->SetTitle("Jpsi Rho");
h_jpsi_perp2[x]->SetTitle("Jpsi Perp^{2}");
h_jpsi_pt[x]->SetTitle("Jpsi p_{T}");
h_jpsi_perp[x]->SetTitle("Jpsi Perp");
h_jpsi_et2[x]->SetTitle("Jpsi E^{2}_{T}");
h_jpsi_et[x]->SetTitle("Jpsi E_{T}");
h_jpsi_Mag2[x]->SetTitle("Jpsi Mag^{2}");
h_jpsi_Mag[x]->SetTitle("Jpsi Mag");
h_jpsi_M[x]->SetTitle("Jpsi M");
h_jpsi_Mt2[x]->SetTitle("Jpsi Mt^{2}");
h_jpsi_Mt[x]->SetTitle("Jpsi Mt");
h_jpsi_beta[x]->SetTitle("Jpsi Beta");
h_jpsi_gamma[x]->SetTitle("Jpsi Gamma");
h_jpsi_plus[x]->SetTitle("Jpsi Plus");
h_jpsi_minus[x]->SetTitle("Jpsi Minus");
h_jpsi_Rap[x]->SetTitle("Jpsi Rap");
h_jpsi_eta[x]->SetTitle("Jpsi Eta");
h_jpsi_psuedorap[x]->SetTitle("Jpsi Psueodorap");

h_muplus_x[x]->SetTitle("MuPlus X");
h_muplus_y[x]->SetTitle("MuPlus Y");
h_muplus_z[x]->SetTitle("MuPlus Z");
h_muplus_px[x]->SetTitle("MuPlus p_{X}");
h_muplus_py[x]->SetTitle("MuPlus p_{Y}");
h_muplus_pz[x]->SetTitle("MuPlus p_{Z}");
h_muplus_t[x]->SetTitle("MuPlus T");
h_muplus_Energy[x]->SetTitle("MuPlus Energy");
h_muplus_theta[x]->SetTitle("MuPlus Theta");
h_muplus_costheta[x]->SetTitle("MuPlus CosTheta");
h_muplus_phi[x]->SetTitle("MuPlus Phi");
h_muplus_rho[x]->SetTitle("MuPlus Rho");
h_muplus_perp2[x]->SetTitle("MuPlus Perp^{2}");
h_muplus_pt[x]->SetTitle("MuPlus p_{T}");
h_muplus_perp[x]->SetTitle("MuPlus Perp");
h_muplus_et2[x]->SetTitle("MuPlus E^{2}_{T}");
h_muplus_et[x]->SetTitle("MuPlus E_{T}");
//h_muplus_Mag2[x]->SetTitle("MuPlus Mag^{2}");
//h_muplus_Mag[x]->SetTitle("MuPlus Mag");
//h_muplus_M[x]->SetTitle("MuPlus M");
h_muplus_Mt2[x]->SetTitle("MuPlus Mt^{2}");
h_muplus_Mt[x]->SetTitle("MuPlus Mt");
h_muplus_beta[x]->SetTitle("MuPlus Beta");
h_muplus_gamma[x]->SetTitle("MuPlus Gamma");
h_muplus_plus[x]->SetTitle("MuPlus Plus");
h_muplus_minus[x]->SetTitle("MuPlus Minus");
h_muplus_Rap[x]->SetTitle("MuPlus Rap");
h_muplus_eta[x]->SetTitle("MuPlus Eta");
h_muplus_psuedorap[x]->SetTitle("MuPlus Psueodorap");

  
  }
  
  
   h_nPriVtx[1]->Draw();
   h_nPriVtx[0]->Draw("same");
   leg->Draw();
   c1->SaveAs("nPriVtx.pdf");
   h_vertexWeight[0]->Draw();
   h_vertexWeight[1]->Draw("same");
   leg->Draw();
   c1->SaveAs("vertexWeight.pdf");
   h_sumPTPV[0]->Draw();
   h_sumPTPV[1]->Draw("same");
   leg->Draw();
   c1->SaveAs("sumPTPV.pdf");
   h_countTksOfPV[0]->Draw();
   h_countTksOfPV[1]->Draw("same");
   leg->Draw();
   c1->SaveAs("countTksOfPV.pdf");
//   h_JpsiMuScleMassCorr[0]->Draw();
//   h_JpsiMuScleMassCorr[1]->Draw("same");
//   leg->Draw();
//   c1->SaveAs("JpsiMuScleMassCorr.pdf");
//   h_JpsiMuScleMassErr[0]->Draw();
//   h_JpsiMuScleMassErr[1]->Draw("same");
//   leg->Draw();
//   c1->SaveAs("JpsiMuScleMassErr.pdf");
   h_JpsiMassErr[1]->Draw();
   h_JpsiMassErr[0]->Draw("same");
   leg->Draw();
   c1->SaveAs("JpsiMassErr.pdf");
//   h_sigmaPtPos[0]->Draw();
//   h_sigmaPtPos[1]->Draw("same");
//   leg->Draw();
//   c1->SaveAs("sigmaPtPos.pdf");
//   h_sigmaPtNeg[0]->Draw();
//   h_sigmaPtNeg[1]->Draw("same");
//   leg->Draw();
//   c1->SaveAs("sigmaPtNeg.pdf");
   h_Jpsict[0]->Draw();
   h_Jpsict[1]->Draw("same");
   leg->Draw();
   c1->SaveAs("Jpsict.pdf");
   h_JpsictErr[1]->Draw();
   h_JpsictErr[0]->Draw("same");
   leg->Draw();
   c1->SaveAs("JpsictErr.pdf");
   h_JpsiVprob[0]->Draw();
   h_JpsiVprob[1]->Draw("same");
   leg->Draw();
   c1->SaveAs("JpsiVprob.pdf");
   h_JpsiDistM1[1]->Draw();
   h_JpsiDistM1[0]->Draw("same");
   leg->Draw();
   c1->SaveAs("JpsiDistM1.pdf");
   h_JpsiDphiM1[1]->Draw();
   h_JpsiDphiM1[0]->Draw("same");
   leg->Draw();
   c1->SaveAs("JpsiDphiM1.pdf");
   h_JpsiDrM1[1]->Draw();
   h_JpsiDrM1[0]->Draw("same");
   leg->Draw();
   c1->SaveAs("JpsiDrM1.pdf");
   h_JpsiDistM2[1]->Draw();
   h_JpsiDistM2[0]->Draw("same");
   leg->Draw();
   c1->SaveAs("JpsiDistM2.pdf");
   h_JpsiDphiM2[1]->Draw();
   h_JpsiDphiM2[0]->Draw("same");
   leg->Draw();
   c1->SaveAs("JpsiDphiM2.pdf");
   h_JpsiDrM2[1]->Draw();
   h_JpsiDrM2[0]->Draw("same");
   leg->Draw();
   c1->SaveAs("JpsiDrM2.pdf");
   
h_muminus_x[0]->Draw();
h_muminus_x[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusX.pdf");
h_muminus_y[0]->Draw();
h_muminus_y[1]->Draw("same");
leg->Draw();
c1->SaveAs("mumimusY.pdf");
h_muminus_z[0]->Draw();
h_muminus_z[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusZ.pdf");
h_muminus_px[0]->Draw();
h_muminus_px[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusPx.pdf");
h_muminus_py[0]->Draw();
h_muminus_py[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusPy.pdf");
h_muminus_pz[0]->Draw();
h_muminus_pz[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusPz.pdf");
h_muminus_t[0]->Draw();
h_muminus_t[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusT.pdf");
h_muminus_Energy[0]->Draw();
h_muminus_Energy[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusEnergy.pdf");
h_muminus_theta[0]->Draw();
h_muminus_theta[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusTheta.pdf");
h_muminus_costheta[0]->Draw();
h_muminus_costheta[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusCosTheta.pdf");
h_muminus_phi[0]->Draw();
h_muminus_phi[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusPhi.pdf");
h_muminus_rho[0]->Draw();
h_muminus_rho[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusRho.pdf");
h_muminus_perp2[0]->Draw();
h_muminus_perp2[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusPerp2.pdf");
h_muminus_pt[0]->Draw();
h_muminus_pt[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminuspT.pdf");
h_muminus_perp[0]->Draw();
h_muminus_perp[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusperp.pdf");
h_muminus_et2[0]->Draw();
h_muminus_et2[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusET2.pdf");
h_muminus_et[0]->Draw();
h_muminus_et[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusET.pdf");
//h_muminus_Mag2[0]->Draw();
//h_muminus_Mag2[1]->Draw("same");
//leg->Draw();
//c1->SaveAs("muminusMAG2.pdf");
//h_muminus_Mag[0]->Draw();
//h_muminus_Mag[1]->Draw("same");
//leg->Draw();
//c1->SaveAs("muminusMAG.pdf");
//h_muminus_M[0]->Draw();
//h_muminus_M[1]->Draw("same");
//leg->Draw();
//c1->SaveAs("muminusM.pdf");
h_muminus_Mt2[0]->Draw();
h_muminus_Mt2[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusMt2.pdf");
h_muminus_Mt[0]->Draw();
h_muminus_Mt[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusMt.pdf");
h_muminus_beta[1]->Draw();
h_muminus_beta[0]->Draw("same");
leg->Draw();
c1->SaveAs("muminusbeta.pdf");
h_muminus_gamma[0]->Draw();
h_muminus_gamma[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusgamma.pdf");
h_muminus_plus[0]->Draw();
h_muminus_plus[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusPlus.pdf");
h_muminus_minus[0]->Draw();
h_muminus_minus[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusMinus.pdf");
h_muminus_Rap[0]->Draw();
h_muminus_Rap[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusRap.pdf");
h_muminus_eta[0]->Draw();
h_muminus_eta[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusEta.pdf");
h_muminus_psuedorap[0]->Draw();
h_muminus_psuedorap[1]->Draw("same");
leg->Draw();
c1->SaveAs("muminusPsuedorap.pdf");

h_jpsi_x[1]->Draw();
h_jpsi_x[0]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiX.pdf");
h_jpsi_y[0]->Draw();
h_jpsi_y[1]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiY.pdf");
h_jpsi_z[0]->Draw();
h_jpsi_z[1]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiZ.pdf");
h_jpsi_px[1]->Draw();
h_jpsi_px[0]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiPx.pdf");
h_jpsi_py[1]->Draw();
h_jpsi_py[0]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiPy.pdf");
h_jpsi_pz[0]->Draw();
h_jpsi_pz[1]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiPz.pdf");
h_jpsi_t[1]->Draw();
h_jpsi_t[0]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiT.pdf");
h_jpsi_Energy[1]->Draw();
h_jpsi_Energy[0]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiEnergy.pdf");
h_jpsi_theta[0]->Draw();
h_jpsi_theta[1]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiTheta.pdf");
h_jpsi_costheta[0]->Draw();
h_jpsi_costheta[1]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiCosTheta.pdf");
h_jpsi_phi[0]->Draw();
h_jpsi_phi[1]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiPhi.pdf");
h_jpsi_rho[1]->Draw();
h_jpsi_rho[0]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiRho.pdf");
h_jpsi_perp2[1]->Draw();
h_jpsi_perp2[0]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiPerp2.pdf");
h_jpsi_pt[1]->Draw();
h_jpsi_pt[0]->Draw("same");
leg->Draw();
c1->SaveAs("jpsipT.pdf");
h_jpsi_perp[1]->Draw();
h_jpsi_perp[0]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiperp.pdf");
h_jpsi_et2[1]->Draw();
h_jpsi_et2[0]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiET2.pdf");
h_jpsi_et[1]->Draw();
h_jpsi_et[0]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiET.pdf");
h_jpsi_Mag2[1]->Draw();
h_jpsi_Mag2[0]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiMAG2.pdf");
h_jpsi_Mag[1]->Draw();
h_jpsi_Mag[0]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiMAG.pdf");
h_jpsi_M[1]->Draw();
h_jpsi_M[0]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiM.pdf");
h_jpsi_Mt2[1]->Draw();
h_jpsi_Mt2[0]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiMt2.pdf");
h_jpsi_Mt[1]->Draw();
h_jpsi_Mt[0]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiMt.pdf");
h_jpsi_beta[1]->Draw();
h_jpsi_beta[0]->Draw("same");
leg->Draw();
c1->SaveAs("jpsibeta.pdf");
h_jpsi_gamma[1]->Draw();
h_jpsi_gamma[0]->Draw("same");
leg->Draw();
c1->SaveAs("jpsigamma.pdf");
h_jpsi_plus[0]->Draw();
h_jpsi_plus[1]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiPlus.pdf");
h_jpsi_minus[1]->Draw();
h_jpsi_minus[0]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiMinus.pdf");
h_jpsi_Rap[0]->Draw();
h_jpsi_Rap[1]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiRap.pdf");
h_jpsi_eta[0]->Draw();
h_jpsi_eta[1]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiEta.pdf");
h_jpsi_psuedorap[0]->Draw();
h_jpsi_psuedorap[1]->Draw("same");
leg->Draw();
c1->SaveAs("jpsiPsuedorap.pdf");

h_muplus_x[0]->Draw();
h_muplus_x[1]->Draw("same");
leg->Draw();
c1->SaveAs("muplusX.pdf");
h_muplus_y[0]->Draw();
h_muplus_y[1]->Draw("same");
leg->Draw();
c1->SaveAs("mumimusY.pdf");
h_muplus_z[0]->Draw();
h_muplus_z[1]->Draw("same");
leg->Draw();
c1->SaveAs("muplusZ.pdf");
h_muplus_px[0]->Draw();
h_muplus_px[1]->Draw("same");
leg->Draw();
c1->SaveAs("muplusPx.pdf");
h_muplus_py[0]->Draw();
h_muplus_py[1]->Draw("same");
leg->Draw();
c1->SaveAs("muplusPy.pdf");
h_muplus_pz[0]->Draw();
h_muplus_pz[1]->Draw("same");
leg->Draw();
c1->SaveAs("muplusPz.pdf");
h_muplus_t[0]->Draw();
h_muplus_t[1]->Draw("same");
leg->Draw();
c1->SaveAs("muplusT.pdf");
h_muplus_Energy[0]->Draw();
h_muplus_Energy[1]->Draw("same");
leg->Draw();
c1->SaveAs("muplusEnergy.pdf");
h_muplus_theta[0]->Draw();
h_muplus_theta[1]->Draw("same");
leg->Draw();
c1->SaveAs("muplusTheta.pdf");
h_muplus_costheta[0]->Draw();
h_muplus_costheta[1]->Draw("same");
leg->Draw();
c1->SaveAs("muplusCosTheta.pdf");
h_muplus_phi[1]->Draw();
h_muplus_phi[0]->Draw("same");
leg->Draw();
c1->SaveAs("muplusPhi.pdf");
h_muplus_rho[0]->Draw();
h_muplus_rho[1]->Draw("same");
leg->Draw();
c1->SaveAs("muplusRho.pdf");
h_muplus_perp2[0]->Draw();
h_muplus_perp2[1]->Draw("same");
leg->Draw();
c1->SaveAs("muplusPerp2.pdf");
h_muplus_pt[0]->Draw();
h_muplus_pt[1]->Draw("same");
leg->Draw();
c1->SaveAs("mupluspT.pdf");
h_muplus_perp[0]->Draw();
h_muplus_perp[1]->Draw("same");
leg->Draw();
c1->SaveAs("muplusperp.pdf");
h_muplus_et2[0]->Draw();
h_muplus_et2[1]->Draw("same");
leg->Draw();
c1->SaveAs("muplusET2.pdf");
h_muplus_et[0]->Draw();
h_muplus_et[1]->Draw("same");
leg->Draw();
c1->SaveAs("muplusET.pdf");
//h_muplus_Mag2[0]->Draw();
//h_muplus_Mag2[1]->Draw("same");
//leg->Draw();
//c1->SaveAs("muplusMAG2.pdf");
//h_muplus_Mag[0]->Draw();
//h_muplus_Mag[1]->Draw("same");
//leg->Draw();
//c1->SaveAs("muplusMAG.pdf");
//h_muplus_M[0]->Draw();
//h_muplus_M[1]->Draw("same");
//leg->Draw();
//c1->SaveAs("muplusM.pdf");
h_muplus_Mt2[0]->Draw();
h_muplus_Mt2[1]->Draw("same");
leg->Draw();
c1->SaveAs("muplusMt2.pdf");
h_muplus_Mt[0]->Draw();
h_muplus_Mt[1]->Draw("same");
leg->Draw();
c1->SaveAs("muplusMt.pdf");
h_muplus_beta[1]->Draw();
h_muplus_beta[0]->Draw("same");
leg->Draw();
c1->SaveAs("muplusbeta.pdf");
h_muplus_gamma[0]->Draw();
h_muplus_gamma[1]->Draw("same");
leg->Draw();
c1->SaveAs("muplusgamma.pdf");
h_muplus_plus[0]->Draw();
h_muplus_plus[1]->Draw("same");
leg->Draw();
c1->SaveAs("muplusPlus.pdf");
h_muplus_minus[0]->Draw();
h_muplus_minus[1]->Draw("same");
leg->Draw();
c1->SaveAs("muplusMinus.pdf");
h_muplus_Rap[1]->Draw();
h_muplus_Rap[0]->Draw("same");
leg->Draw();
c1->SaveAs("muplusRap.pdf");
h_muplus_eta[1]->Draw();
h_muplus_eta[0]->Draw("same");
leg->Draw();
c1->SaveAs("muplusEta.pdf");
h_muplus_psuedorap[1]->Draw();
h_muplus_psuedorap[0]->Draw("same");
leg->Draw();
c1->SaveAs("muplusPsuedorap.pdf");
    
 
 
}
