{
mkdir Systematics/cutNPriVtx_smallerpT2/
mkdir Systematics/cutNPriVtx_smallerpT2/cutNPriVtx_smallerpT2_FrameworkIII/
mkdir Systematics/cutNPriVtx_smallerpT2/cutNPriVtx_smallerpT2_FrameworkIII/ChangedTGraph/
mkdir Systematics/cutNPriVtx_smallerpT2/cutNPriVtx_smallerpT2_FrameworkII/
mkdir Systematics/cutNPriVtx_smallerpT2/cutNPriVtx_smallerpT2_FrameworkII/ChangedTGraph/
mkdir Systematics/cutNPriVtx_smallerpT2/cutNPriVtx_smallerpT2_FrameworkI/
mkdir Systematics/cutNPriVtx_smallerpT2/cutNPriVtx_smallerpT2_FrameworkI/ChangedTGraph/
mkdir Systematics/cutNPriVtx_smallerpT2/cutNPriVtx_smallerpT2_Parametrization/
mkdir Systematics/cutNPriVtx_smallerpT2/cutNPriVtx_smallerpT2_Parametrization/ChangedTGraph/
mkdir Systematics/cutNPriVtx_smallerpT2/cutNPriVtx_smallerpT2_RhoFactor/
mkdir Systematics/cutNPriVtx_smallerpT2/cutNPriVtx_smallerpT2_RhoFactor/ChangedTGraph/
mkdir Systematics/cutNPriVtx_smallerpT2/cutNPriVtx_smallerpT2_TnP_model/
mkdir Systematics/cutNPriVtx_smallerpT2/cutNPriVtx_smallerpT2_TnP_model/ChangedTGraph/
mkdir /data/users/ferraioc/Polarization/Modified/Data/cutNPriVtx_smallerpT2_BiasCorrection/


#cp Systematics/cutNPriVtx_4CPMBins_FrameworkIII/ChangedTGraph/* Systematics/cutNPriVtx/cutNPriVtx_FrameworkIII/ChangedTGraph/
#cp Systematics/cutNPriVtx_4CPMBins_FrameworkII/ChangedTGraph/* Systematics/cutNPriVtx/cutNPriVtx_FrameworkII/ChangedTGraph/
#cp Systematics/cutNPriVtx_4CPMBins_FrameworkI/ChangedTGraph/* Systematics/cutNPriVtx/cutNPriVtx_FrameworkI/ChangedTGraph/
#cp Systematics/cutNPriVtx_4CPMBins_Parametrization/ChangedTGraph/* Systematics/cutNPriVtx/cutNPriVtx_Parametrization/ChangedTGraph/
#cp Systematics/cutNPriVtx_4CPMBins_RhoFactor/ChangedTGraph/* Systematics/cutNPriVtx/cutNPriVtx_RhoFactor/ChangedTGraph/
#cp Systematics/cutNPriVtx_4CPMBins_TnP_model/ChangedTGraph/* Systematics/cutNPriVtx/cutNPriVtx_TnP_model/ChangedTGraph/

cp Systematics/cutNPriVtx_FrameworkIII_smallerpT2/ChangedTGraph/* Systematics/cutNPriVtx_smallerpT2/cutNPriVtx_smallerpT2_FrameworkIII/ChangedTGraph/
cp Systematics/cutNPriVtx_FrameworkII_smallerpT2/ChangedTGraph/* Systematics/cutNPriVtx_smallerpT2/cutNPriVtx_smallerpT2_FrameworkII/ChangedTGraph/
cp Systematics/cutNPriVtx_FrameworkI_smallerpT2/ChangedTGraph/* Systematics/cutNPriVtx_smallerpT2/cutNPriVtx_smallerpT2_FrameworkI/ChangedTGraph/
cp Systematics/cutNPriVtx_Parametrization_smallerpT2/ChangedTGraph/* Systematics/cutNPriVtx_smallerpT2/cutNPriVtx_smallerpT2_Parametrization/ChangedTGraph/
cp Systematics/cutNPriVtx_RhoFactor_smallerpT2/ChangedTGraph/* Systematics/cutNPriVtx_smallerpT2/cutNPriVtx_smallerpT2_RhoFactor/ChangedTGraph/
cp Systematics/cutNPriVtx_TnP_model_smallerpT2/ChangedTGraph/* Systematics/cutNPriVtx_smallerpT2/cutNPriVtx_smallerpT2_TnP_model/ChangedTGraph/
cp Systematics/cutNPriVtx_BiasCorrection_smallerpT2/ChangedTGraph/* /data/users/ferraioc/Polarization/Modified/Data/cutNPriVtx_smallerpT2_BiasCorrection/



}